# Site settings
title: On the Rocks

baseurl: "/OnTheRocks" # the subpath of your site, e.g. /blog/
url: "https://projects.allejo.io" # the base hostname & protocol for your site

markdown: kramdown

kramdown:
  input: GFM
  auto_ids: true

fa_version: 4.6.3

exclude:
  - Gemfile
  - Gemfile.lock
  - dist
  - sassdoc
  - node_modules

include:
  - _pages